name: Golang Build
description: Building golang binaries against different versions of golang
author: https://github.com/buildkite
requirements:
  - docker
configuration:
  properties:
    build:
      type: string
    import:
      type: string
    targets:
      type: array
      items:
        type: object
        properties:
          version:
            type: string
          goos:
            type: string
          goarch:
            type: string
          goarm:
            type: number
          gomodule:
            type: string
  required: []
  additionalProperties: false
