steps:
  - label: run bats tests
    plugins:
      docker-compose#v1.2.1:
        run: tests

  - label: ":bash: Shellcheck"
    plugins:
      shellcheck#v1.0.1:
        files:
          - hooks/*

  - label: ":sparkles: Linter"
    plugins:
      plugin-linter#v1.0.0:
        name: golang-build